language: java
jdk: openjdk7
install :
  - mvn install -DskipTests # TODO: actually run tests after all the other kinks are worked out
script:
  - cd /tmp/
  - mvn org.openmrs.maven.plugins:openmrs-sdk-maven-plugin:3.13.1-SNAPSHOT:build-distro -Ddir=docker -Ddistro=referenceapplication:2.9.0-SNAPSHOT -DbatchAnswers=n
  - ls -lah ./docker
#deploy:
#  provider: script
#  script: ./deploy.sh
#  skip_cleanup: true
#  on:
#    tags: true
