language: java
jdk: openjdk7
install :
  - mvn install -DskipTests # TODO: actually run tests after all the other kinks are worked out
  - mvn org.openmrs.maven.plugins:openmrs-sdk-maven-plugin:3.13.1-SNAPSHOT:setup-sdk
script:
  - cd /tmp/
  - mvn org.openmrs.maven.plugins:openmrs-sdk-maven-plugin:3.13.1-SNAPSHOT:build-distro -Ddir=docker -Ddistro=org.openmrs.distro:referenceapplication:2.8.0 -DbatchAnswers=n
  - ls -lah ./docker
#deploy:
#  provider: script
#  script: ./deploy.sh
#  skip_cleanup: true
#  on:
#    tags: true
